name: Go

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22.5"

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: v1.54.2
          args: --timeout 5m0s --verbose --modules-download-mode readonly

      - name: Run staticcheck # see: staticcheck.io
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.2"
          install-go: false
          min-go-version: 1.21

      - name: Run tests
        run: go test ./test
